---
title: "Exam 1"
author: "Westley Cook"
date: "2/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

1. The highest emissions are from the country X.

2. The number of countries that have neither ratified nor approved of the treaty is X. (Acceptance and accession do not count as approval).

3. The longest number of days between signature and ratification (for a country that has successfully ratified) is X days.

4. The number of ratifying countries whose name ends with “stan” is X.

Now access World Bank emissions data in the exam 1 folder on canvas. Download a copy of this data from the provided link, create a directory named “raw-data” within your project, and move the data (which should be called “WB_co2_emissions.csv”) to that directory. Commit those changes. Read in the data, clean the variable names using janitor, and then answer the following Mad Libs.

5. In 1960, the country with the highest emissions was X.

6. The average emissions in 2000 was X metric tons per capita. (Round so that there are only two digits after the decimal point.)

## Question 2

## Question 3